name: modu_messenger_firebase
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #  아이콘
  flutter_launcher_icons: ^0.13.0
  cupertino_icons: ^1.0.6

  # fire base
  firebase_core : ^2.0.0
  firebase_auth : ^4.1.3
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.1.0
  firebase_messaging: ^14.9.4

  # google 인증
  google_sign_in : ^5.4.2

  # 이미지
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6
  flutter_svg: ^2.0.9

  # 권한
  permission_handler: ^11.3.1

  # 글로벌 변수 관리
  provider: ^6.0.1


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets :
    - assets/images/google.png
    - assets/images/icon.png
    - assets/icons/talkIcon.svg
    - assets/icons/locationIcon.svg
    - assets/icons/chatIcon.svg
    - assets/icons/moreIcon.svg
    - assets/icons/readIcon.svg
    - assets/icons/readOnIcon.svg
    - assets/icons/plusIcon.svg
    - assets/icons/sendIcon.svg
  fonts :
    - family: NotoSansKR
      fonts :
        - asset:  assets/fonts/NotoSansKR-Regular.ttf
        - asset:  assets/fonts/NotoSansKR-Bold.ttf
          weight : 700
