name: modu_messanger
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.2.0

  firebase_auth : ^4.1.3

  google_sign_in: ^5.4.2

  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  ios: true
  image_path: "images/icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  assets:
    - images/
  uses-material-design: true