// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQGpDZYY6mlhhF-kYQt4UW9gq4mrjVrms',
    appId: '1:483669063544:web:987555626c947b465c7a8d',
    messagingSenderId: '483669063544',
    projectId: 'wechat-703d0',
    authDomain: 'wechat-703d0.firebaseapp.com',
    storageBucket: 'wechat-703d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx6zauinM9VDLXTrw6CpnGYrx5k68d3Mw',
    appId: '1:483669063544:android:4c453f77480ee1945c7a8d',
    messagingSenderId: '483669063544',
    projectId: 'wechat-703d0',
    storageBucket: 'wechat-703d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Tt1Uy9NDjQHDsIbKOjpoDKoysx68NeI',
    appId: '1:483669063544:ios:681cc0bf287f34ff5c7a8d',
    messagingSenderId: '483669063544',
    projectId: 'wechat-703d0',
    storageBucket: 'wechat-703d0.appspot.com',
    iosBundleId: 'com.example.moduMessanger',
  );
}
